### ISSUE TITLE
Max analog ISO can be higher

### ISSUE THREAD

**Issue by Sergio677** [mirsadm/motioncam#25]
Hi.
Great app for 1+7! Great NR in raw.
But max iso 3200, while max analog in cam API - 5699. Maybe you can fix this?

Also, max shutter is 1 sec. Stock cam can set up to 30 sec. Gcam too.

Very thanks!

**Comment by mirsadm** [comment]
I have a 1+7 myself and the phone reports 3200 as the max iso unfortunately. I have noticed it's happy to go above that when exposure is set to auto.

As for the shutter speed, I set the limit to 1 sec artiificially to make it a little bit easier to select the shutter speed because the slider control is not very good for this purpose. I'll take that out so you can select higher values.
